Login navigation
wolox-training/mr-android pull request #2
Opened 2021-04-06 20:51 UTC by Marcosnr97

### Summary
Added signup activity and navigation from login activity

2021-04-06 21:32 UTC, jcruz-wolox requested changes
I just have one comment, the rest is very well.

2021-04-06 21:32 UTC, jcruz-wolox commented on app/src/main/res/layout/fragment_signup.xml
> +            android:layout_marginTop="5dp"
Remove hardcode dimen, you have add it in dimens.xml

2021-04-07 12:43 UTC, ffasitella requested changes
Just two comments 😄

2021-04-07 12:43 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/signup/SignupPresenter.kt
> +    }
Delete this empty method

2021-04-07 12:43 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/signup/SignupFragment.kt
> +    override fun goToLogin() = LoginActivity.start(requireContext())
You can use `onBackPressed()` method instead of instantiating a new activity

2021-04-07 13:31 UTC, jcruz-wolox approved these changes

2021-04-07 13:34 UTC, ffasitella approved these changes
![](https://media.giphy.com/media/dxocWugDZRyG4/giphy.gif)

2021-04-07 13:43 UTC, merged